function New-RollbackPlan {
    <#
    .SYNOPSIS
        Creates a rollback plan for policy changes.
    
    .DESCRIPTION
        Generates a documented rollback plan with backups and procedures for reverting changes.
        Creates a markdown document with step-by-step rollback instructions.
    
    .PARAMETER PolicyIds
        Array of policy IDs to include in the rollback plan.
    
    .PARAMETER PolicyType
        The type of policies.
    
    .PARAMETER OutputPath
        Path to save the rollback plan (defaults to current directory).
    
    .PARAMETER Description
        Description of the changes being made.
    
    .EXAMPLE
        New-RollbackPlan -PolicyIds @("abc123", "def456") -PolicyType Compliance -Description "Q1 2026 compliance update"
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string[]]$PolicyIds,
        
        [Parameter(Mandatory = $true)]
        [ValidateSet('Compliance', 'Configuration', 'AppProtection', 'AppConfiguration')]
        [string]$PolicyType,
        
        [Parameter(Mandatory = $false)]
        [string]$OutputPath = ".",
        
        [Parameter(Mandatory = $false)]
        [string]$Description = "Policy change rollback plan"
    )
    
    try {
        Write-Host "Creating rollback plan..." -ForegroundColor Yellow
        
        $timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
        $backupFiles = @()
        
        # Create backups for all policies
        foreach ($policyId in $PolicyIds) {
            Write-Host "Backing up policy $policyId..." -ForegroundColor Cyan
            $backupFile = Backup-PolicyConfiguration -PolicyId $policyId -PolicyType $PolicyType -BackupPath $OutputPath
            $backupFiles += $backupFile
        }
        
        # Generate rollback plan document
        $planContent = @"
# Rollback Plan

**Generated:** $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
**Description:** $Description

## Overview

This rollback plan provides step-by-step instructions for reverting policy changes made to the following policies:

$($PolicyIds | ForEach-Object { "- Policy ID: $_" } | Out-String)

## Backup Files

The following backup files have been created:

$($backupFiles | ForEach-Object { "- $([System.IO.Path]::GetFileName($_))" } | Out-String)

## Rollback Procedure

### Prerequisites

1. Ensure you have the IntuneScripts PowerShell module loaded
2. Connect to Microsoft Graph with appropriate permissions:
   ``````powershell
   Connect-IntuneGraph
   ``````

### Rollback Steps

$($backupFiles | ForEach-Object { 
$fileName = [System.IO.Path]::GetFileName($_)
@"
#### Restore $fileName

``````powershell
Restore-PolicyConfiguration -BackupFile "$fileName"
``````

"@ } | Out-String)

### Verification Steps

After rollback, verify:

1. Policy assignments have been restored to original groups
2. Devices are receiving the correct policies
3. Compliance status is as expected
4. Run compliance report:
   ``````powershell
   Get-ComplianceReport -PolicyId "<policy-id>" -PolicyType $PolicyType
   ``````

## Rollback Checklist

- [ ] Review backup files and verify completeness
- [ ] Execute rollback commands in sequence
- [ ] Verify policy assignments in Intune portal
- [ ] Check device compliance status
- [ ] Monitor for any errors or issues
- [ ] Document rollback completion and any findings

## Support Contacts

If issues arise during rollback:
- Escalate to Intune administrator
- Reference this document and backup files
- Review Graph API error logs if applicable

---
*This rollback plan was automatically generated by IntuneScripts PowerShell module*
"@

        # Save rollback plan
        $planFileName = "RollbackPlan_$($PolicyType)_$timestamp.md"
        $planFilePath = Join-Path $OutputPath $planFileName
        $planContent | Out-File -FilePath $planFilePath -Encoding UTF8
        
        Write-Host "`nRollback plan created successfully" -ForegroundColor Green
        Write-Host "  Plan file: $planFilePath" -ForegroundColor Cyan
        Write-Host "  Policies backed up: $($PolicyIds.Count)" -ForegroundColor Cyan
        Write-Host "  Backup files: $($backupFiles.Count)" -ForegroundColor Cyan
        
        return @{
            PlanFile = $planFilePath
            BackupFiles = $backupFiles
        }
    }
    catch {
        Write-Error "Failed to create rollback plan: $_"
        throw
    }
}
